version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: renec-postgres
    environment:
      POSTGRES_DB: renec_harvester
      POSTGRES_USER: renec
      POSTGRES_PASSWORD: renec_secure_pass
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U renec -d renec_harvester"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: renec-redis
    command: redis-server --requirepass renec_redis_pass --maxmemory 512mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: renec-redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379:0:renec_redis_pass
    ports:
      - "8081:8081"
    depends_on:
      - redis

  flower:
    image: mher/flower:2.0
    container_name: renec-flower
    command: celery --broker=redis://:renec_redis_pass@redis:6379/0 flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://:renec_redis_pass@redis:6379/0
      - FLOWER_BASIC_AUTH=admin:renec_flower_pass

  prometheus:
    image: prom/prometheus:latest
    container_name: renec-prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    depends_on:
      - postgres
      - redis

  grafana:
    image: grafana/grafana:latest
    container_name: renec-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=renec_grafana_pass
      - GF_INSTALL_PLUGINS=redis-datasource
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: renec-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@renec.local
      PGADMIN_DEFAULT_PASSWORD: renec_pgadmin_pass
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  redis_data:
  prometheus_data:
  grafana_data:
  pgadmin_data:

networks:
  default:
    name: renec-network