global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'renec-harvester'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them
rule_files:
  # - "alerts.yml"
  # - "rules.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # RENEC Harvester API metrics
  - job_name: 'renec-api'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Redis exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'

  # PostgreSQL exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  # Scrapy spider metrics (custom exporter)
  - job_name: 'scrapy-spiders'
    static_configs:
      - targets: ['host.docker.internal:9091']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Celery worker metrics
  - job_name: 'celery-workers'
    static_configs:
      - targets: ['host.docker.internal:9092']
    metrics_path: '/metrics'

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['host.docker.internal:9100']